name: flutter_pagination_pro
description: "A lightweight Flutter pagination package supporting infinite scroll, load more button, and numbered pagination with zero dependencies."
version: 0.0.1
homepage: https://github.com/Masum-MSNR/flutter_pagination_pro
repository: https://github.com/Masum-MSNR/flutter_pagination_pro
issue_tracker: https://github.com/Masum-MSNR/flutter_pagination_pro/issues

topics:
  - pagination
  - infinite-scroll
  - paging
  - list
  - ui

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
